export const newGroupCount = [
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 228,
    lat: null,
    lng: null,
    people_count: 442,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 276,
    region_name: "高尔夫",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 227,
    lat: null,
    lng: null,
    people_count: 236,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 276,
    region_name: "高尔夫",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 226,
    lat: null,
    lng: null,
    people_count: 152,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 276,
    region_name: "高尔夫",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 225,
    lat: null,
    lng: null,
    people_count: 746,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 276,
    region_name: "高尔夫",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 224,
    lat: null,
    lng: null,
    people_count: 724,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 275,
    region_name: "馨悦",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 223,
    lat: null,
    lng: null,
    people_count: 245,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 275,
    region_name: "馨悦",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 222,
    lat: null,
    lng: null,
    people_count: 235,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 275,
    region_name: "馨悦",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 221,
    lat: null,
    lng: null,
    people_count: 1332,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 275,
    region_name: "馨悦",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 220,
    lat: null,
    lng: null,
    people_count: 301,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 274,
    region_name: "香茂",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 219,
    lat: null,
    lng: null,
    people_count: 79,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 274,
    region_name: "香茂",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 218,
    lat: null,
    lng: null,
    people_count: 110,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 274,
    region_name: "香茂",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 217,
    lat: null,
    lng: null,
    people_count: 858,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 274,
    region_name: "香茂",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 216,
    lat: null,
    lng: null,
    people_count: 813,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 273,
    region_name: "领汇",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 215,
    lat: null,
    lng: null,
    people_count: 280,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 273,
    region_name: "领汇",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 214,
    lat: null,
    lng: null,
    people_count: 234,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 273,
    region_name: "领汇",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 213,
    lat: null,
    lng: null,
    people_count: 1295,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 273,
    region_name: "领汇",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 212,
    lat: null,
    lng: null,
    people_count: 486,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 272,
    region_name: "钟悦",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 211,
    lat: null,
    lng: null,
    people_count: 143,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 272,
    region_name: "钟悦",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 210,
    lat: null,
    lng: null,
    people_count: 149,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 272,
    region_name: "钟悦",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 209,
    lat: null,
    lng: null,
    people_count: 981,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 272,
    region_name: "钟悦",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 208,
    lat: null,
    lng: null,
    people_count: 726,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 271,
    region_name: "金姬墩",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 207,
    lat: null,
    lng: null,
    people_count: 270,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 271,
    region_name: "金姬墩",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 206,
    lat: null,
    lng: null,
    people_count: 155,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 271,
    region_name: "金姬墩",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 205,
    lat: null,
    lng: null,
    people_count: 948,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 271,
    region_name: "金姬墩",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 204,
    lat: null,
    lng: null,
    people_count: 884,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 270,
    region_name: "都市",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 203,
    lat: null,
    lng: null,
    people_count: 172,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 270,
    region_name: "都市",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 202,
    lat: null,
    lng: null,
    people_count: 1202,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 270,
    region_name: "都市",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 201,
    lat: null,
    lng: null,
    people_count: 221,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 270,
    region_name: "都市",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 200,
    lat: null,
    lng: null,
    people_count: 717,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 269,
    region_name: "邻瑞",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 199,
    lat: null,
    lng: null,
    people_count: 328,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 269,
    region_name: "邻瑞",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 198,
    lat: null,
    lng: null,
    people_count: 188,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 269,
    region_name: "邻瑞",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 197,
    lat: null,
    lng: null,
    people_count: 1145,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 269,
    region_name: "邻瑞",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 196,
    lat: null,
    lng: null,
    people_count: 1316,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 268,
    region_name: "贵都",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 195,
    lat: null,
    lng: null,
    people_count: 460,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 268,
    region_name: "贵都",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 194,
    lat: null,
    lng: null,
    people_count: 297,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 268,
    region_name: "贵都",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 193,
    lat: null,
    lng: null,
    people_count: 1757,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 268,
    region_name: "贵都",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 192,
    lat: null,
    lng: null,
    people_count: 1178,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 267,
    region_name: "荣域",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 191,
    lat: null,
    lng: null,
    people_count: 365,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 267,
    region_name: "荣域",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 190,
    lat: null,
    lng: null,
    people_count: 166,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 267,
    region_name: "荣域",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 189,
    lat: null,
    lng: null,
    people_count: 1104,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 267,
    region_name: "荣域",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 188,
    lat: null,
    lng: null,
    people_count: 858,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 266,
    region_name: "苏州中心广场",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 187,
    lat: null,
    lng: null,
    people_count: 215,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 266,
    region_name: "苏州中心广场",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 186,
    lat: null,
    lng: null,
    people_count: 162,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 266,
    region_name: "苏州中心广场",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 185,
    lat: null,
    lng: null,
    people_count: 1144,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 266,
    region_name: "苏州中心广场",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 184,
    lat: null,
    lng: null,
    people_count: 270,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 265,
    region_name: "第五元素",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 183,
    lat: null,
    lng: null,
    people_count: 102,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 265,
    region_name: "第五元素",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 182,
    lat: null,
    lng: null,
    people_count: 112,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 265,
    region_name: "第五元素",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 181,
    lat: null,
    lng: null,
    people_count: 793,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 265,
    region_name: "第五元素",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 180,
    lat: null,
    lng: null,
    people_count: 815,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 264,
    region_name: "白塘",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 179,
    lat: null,
    lng: null,
    people_count: 1258,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 264,
    region_name: "白塘",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 178,
    lat: null,
    lng: null,
    people_count: 263,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 264,
    region_name: "白塘",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 177,
    lat: null,
    lng: null,
    people_count: 259,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 264,
    region_name: "白塘",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 176,
    lat: null,
    lng: null,
    people_count: 1477,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 263,
    region_name: "玲珑湾",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 175,
    lat: null,
    lng: null,
    people_count: 488,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 263,
    region_name: "玲珑湾",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 174,
    lat: null,
    lng: null,
    people_count: 299,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 263,
    region_name: "玲珑湾",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 173,
    lat: null,
    lng: null,
    people_count: 1478,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 263,
    region_name: "玲珑湾",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 172,
    lat: null,
    lng: null,
    people_count: 272,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 262,
    region_name: "玲东",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 171,
    lat: null,
    lng: null,
    people_count: 113,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 262,
    region_name: "玲东",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 170,
    lat: null,
    lng: null,
    people_count: 129,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 262,
    region_name: "玲东",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 169,
    lat: null,
    lng: null,
    people_count: 630,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 262,
    region_name: "玲东",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 168,
    lat: null,
    lng: null,
    people_count: 828,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 261,
    region_name: "熙岸",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 167,
    lat: null,
    lng: null,
    people_count: 336,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 261,
    region_name: "熙岸",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 166,
    lat: null,
    lng: null,
    people_count: 212,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 261,
    region_name: "熙岸",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 165,
    lat: null,
    lng: null,
    people_count: 1090,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 261,
    region_name: "熙岸",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 164,
    lat: null,
    lng: null,
    people_count: 426,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 260,
    region_name: "澳韵",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 163,
    lat: null,
    lng: null,
    people_count: 186,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 260,
    region_name: "澳韵",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 162,
    lat: null,
    lng: null,
    people_count: 147,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 260,
    region_name: "澳韵",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 161,
    lat: null,
    lng: null,
    people_count: 953,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 260,
    region_name: "澳韵",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 160,
    lat: null,
    lng: null,
    people_count: 956,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 259,
    region_name: "滨湖",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 159,
    lat: null,
    lng: null,
    people_count: 379,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 259,
    region_name: "滨湖",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 158,
    lat: null,
    lng: null,
    people_count: 216,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 259,
    region_name: "滨湖",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 157,
    lat: null,
    lng: null,
    people_count: 1203,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 259,
    region_name: "滨湖",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 156,
    lat: null,
    lng: null,
    people_count: 477,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 258,
    region_name: "湖畔天城",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 155,
    lat: null,
    lng: null,
    people_count: 161,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 258,
    region_name: "湖畔天城",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 154,
    lat: null,
    lng: null,
    people_count: 147,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 258,
    region_name: "湖畔天城",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 153,
    lat: null,
    lng: null,
    people_count: 1046,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 258,
    region_name: "湖畔天城",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 152,
    lat: null,
    lng: null,
    people_count: 492,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 257,
    region_name: "湖左岸",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 151,
    lat: null,
    lng: null,
    people_count: 122,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 257,
    region_name: "湖左岸",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 150,
    lat: null,
    lng: null,
    people_count: 94,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 257,
    region_name: "湖左岸",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 149,
    lat: null,
    lng: null,
    people_count: 684,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 257,
    region_name: "湖左岸",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 148,
    lat: null,
    lng: null,
    people_count: 701,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 256,
    region_name: "海悦",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 147,
    lat: null,
    lng: null,
    people_count: 216,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 256,
    region_name: "海悦",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 146,
    lat: null,
    lng: null,
    people_count: 215,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 256,
    region_name: "海悦",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 145,
    lat: null,
    lng: null,
    people_count: 1155,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 256,
    region_name: "海悦",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 144,
    lat: null,
    lng: null,
    people_count: 1135,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 255,
    region_name: "海尚",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 143,
    lat: null,
    lng: null,
    people_count: 380,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 255,
    region_name: "海尚",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 142,
    lat: null,
    lng: null,
    people_count: 260,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 255,
    region_name: "海尚",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 141,
    lat: null,
    lng: null,
    people_count: 1309,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 255,
    region_name: "海尚",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 140,
    lat: null,
    lng: null,
    people_count: 1532,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 254,
    region_name: "沁苑",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 139,
    lat: null,
    lng: null,
    people_count: 459,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 254,
    region_name: "沁苑",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 138,
    lat: null,
    lng: null,
    people_count: 278,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 254,
    region_name: "沁苑",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 137,
    lat: null,
    lng: null,
    people_count: 1314,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 254,
    region_name: "沁苑",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 136,
    lat: null,
    lng: null,
    people_count: 1182,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 253,
    region_name: "水巷",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 135,
    lat: null,
    lng: null,
    people_count: 393,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 253,
    region_name: "水巷",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 134,
    lat: null,
    lng: null,
    people_count: 209,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 253,
    region_name: "水巷",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 133,
    lat: null,
    lng: null,
    people_count: 1255,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 253,
    region_name: "水巷",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 132,
    lat: null,
    lng: null,
    people_count: 284,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 252,
    region_name: "水墨",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 131,
    lat: null,
    lng: null,
    people_count: 83,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 252,
    region_name: "水墨",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 130,
    lat: null,
    lng: null,
    people_count: 748,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 252,
    region_name: "水墨",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 129,
    lat: null,
    lng: null,
    people_count: 66,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 252,
    region_name: "水墨",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 128,
    lat: null,
    lng: null,
    people_count: 303,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 251,
    region_name: "欧典",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 127,
    lat: null,
    lng: null,
    people_count: 141,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 251,
    region_name: "欧典",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 126,
    lat: null,
    lng: null,
    people_count: 113,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 251,
    region_name: "欧典",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 125,
    lat: null,
    lng: null,
    people_count: 905,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 251,
    region_name: "欧典",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 124,
    lat: null,
    lng: null,
    people_count: 575,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 250,
    region_name: "枫情水岸",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 123,
    lat: null,
    lng: null,
    people_count: 229,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 250,
    region_name: "枫情水岸",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 122,
    lat: null,
    lng: null,
    people_count: 155,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 250,
    region_name: "枫情水岸",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 121,
    lat: null,
    lng: null,
    people_count: 1066,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 250,
    region_name: "枫情水岸",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 120,
    lat: null,
    lng: null,
    people_count: 614,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 249,
    region_name: "朗科",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 119,
    lat: null,
    lng: null,
    people_count: 1213,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 249,
    region_name: "朗科",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 118,
    lat: null,
    lng: null,
    people_count: 219,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 249,
    region_name: "朗科",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 117,
    lat: null,
    lng: null,
    people_count: 197,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 249,
    region_name: "朗科",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 116,
    lat: null,
    lng: null,
    people_count: 1080,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 248,
    region_name: "景城",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 115,
    lat: null,
    lng: null,
    people_count: 250,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 248,
    region_name: "景城",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 114,
    lat: null,
    lng: null,
    people_count: 850,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 248,
    region_name: "景城",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 113,
    lat: null,
    lng: null,
    people_count: 198,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 248,
    region_name: "景城",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 112,
    lat: null,
    lng: null,
    people_count: 457,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 247,
    region_name: "星耀",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 111,
    lat: null,
    lng: null,
    people_count: 162,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 247,
    region_name: "星耀",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 110,
    lat: null,
    lng: null,
    people_count: 192,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 247,
    region_name: "星耀",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 109,
    lat: null,
    lng: null,
    people_count: 974,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 247,
    region_name: "星耀",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 108,
    lat: null,
    lng: null,
    people_count: 668,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 246,
    region_name: "星湖",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 107,
    lat: null,
    lng: null,
    people_count: 207,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 246,
    region_name: "星湖",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 106,
    lat: null,
    lng: null,
    people_count: 168,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 246,
    region_name: "星湖",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 105,
    lat: null,
    lng: null,
    people_count: 916,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 246,
    region_name: "星湖",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 104,
    lat: null,
    lng: null,
    people_count: 892,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 245,
    region_name: "星桂",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 103,
    lat: null,
    lng: null,
    people_count: 224,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 245,
    region_name: "星桂",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 102,
    lat: null,
    lng: null,
    people_count: 178,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 245,
    region_name: "星桂",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 101,
    lat: null,
    lng: null,
    people_count: 1244,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 245,
    region_name: "星桂",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 100,
    lat: null,
    lng: null,
    people_count: 342,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 244,
    region_name: "星公元",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 99,
    lat: null,
    lng: null,
    people_count: 96,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 244,
    region_name: "星公元",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 98,
    lat: null,
    lng: null,
    people_count: 137,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 244,
    region_name: "星公元",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 97,
    lat: null,
    lng: null,
    people_count: 848,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 244,
    region_name: "星公元",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 96,
    lat: null,
    lng: null,
    people_count: 810,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 243,
    region_name: "时代广场南",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 95,
    lat: null,
    lng: null,
    people_count: 322,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 243,
    region_name: "时代广场南",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 94,
    lat: null,
    lng: null,
    people_count: 183,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 243,
    region_name: "时代广场南",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 93,
    lat: null,
    lng: null,
    people_count: 1245,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 243,
    region_name: "时代广场南",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 92,
    lat: null,
    lng: null,
    people_count: 949,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 242,
    region_name: "时代广场北",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 91,
    lat: null,
    lng: null,
    people_count: 346,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 242,
    region_name: "时代广场北",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 90,
    lat: null,
    lng: null,
    people_count: 215,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 242,
    region_name: "时代广场北",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 89,
    lat: null,
    lng: null,
    people_count: 1322,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 242,
    region_name: "时代广场北",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 88,
    lat: null,
    lng: null,
    people_count: 277,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 241,
    region_name: "时代上城南",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 87,
    lat: null,
    lng: null,
    people_count: 127,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 241,
    region_name: "时代上城南",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 86,
    lat: null,
    lng: null,
    people_count: 722,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 241,
    region_name: "时代上城南",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 85,
    lat: null,
    lng: null,
    people_count: 123,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 241,
    region_name: "时代上城南",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 84,
    lat: null,
    lng: null,
    people_count: 365,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 240,
    region_name: "时代上城北",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 83,
    lat: null,
    lng: null,
    people_count: 132,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 240,
    region_name: "时代上城北",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 82,
    lat: null,
    lng: null,
    people_count: 162,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 240,
    region_name: "时代上城北",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 81,
    lat: null,
    lng: null,
    people_count: 815,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 240,
    region_name: "时代上城北",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 80,
    lat: null,
    lng: null,
    people_count: 509,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 239,
    region_name: "方悦",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 79,
    lat: null,
    lng: null,
    people_count: 142,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 239,
    region_name: "方悦",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 78,
    lat: null,
    lng: null,
    people_count: 160,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 239,
    region_name: "方悦",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 77,
    lat: null,
    lng: null,
    people_count: 1054,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 239,
    region_name: "方悦",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 76,
    lat: null,
    lng: null,
    people_count: 1063,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 238,
    region_name: "新鑫",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 75,
    lat: null,
    lng: null,
    people_count: 372,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 238,
    region_name: "新鑫",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 74,
    lat: null,
    lng: null,
    people_count: 290,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 238,
    region_name: "新鑫",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 73,
    lat: null,
    lng: null,
    people_count: 1702,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 238,
    region_name: "新鑫",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 72,
    lat: null,
    lng: null,
    people_count: 1331,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 237,
    region_name: "新未来",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 71,
    lat: null,
    lng: null,
    people_count: 422,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 237,
    region_name: "新未来",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 70,
    lat: null,
    lng: null,
    people_count: 260,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 237,
    region_name: "新未来",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 69,
    lat: null,
    lng: null,
    people_count: 1290,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 237,
    region_name: "新未来",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 68,
    lat: null,
    lng: null,
    people_count: 1573,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 236,
    region_name: "新城",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 67,
    lat: null,
    lng: null,
    people_count: 449,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 236,
    region_name: "新城",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 66,
    lat: null,
    lng: null,
    people_count: 243,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 236,
    region_name: "新城",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 65,
    lat: null,
    lng: null,
    people_count: 1400,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 236,
    region_name: "新城",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 64,
    lat: null,
    lng: null,
    people_count: 1202,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 235,
    region_name: "新加",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 63,
    lat: null,
    lng: null,
    people_count: 1212,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 235,
    region_name: "新加",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 62,
    lat: null,
    lng: null,
    people_count: 330,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 235,
    region_name: "新加",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 61,
    lat: null,
    lng: null,
    people_count: 235,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 235,
    region_name: "新加",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 60,
    lat: null,
    lng: null,
    people_count: 1022,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 234,
    region_name: "师惠",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 59,
    lat: null,
    lng: null,
    people_count: 318,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 234,
    region_name: "师惠",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 58,
    lat: null,
    lng: null,
    people_count: 271,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 234,
    region_name: "师惠",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 57,
    lat: null,
    lng: null,
    people_count: 1592,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 234,
    region_name: "师惠",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 56,
    lat: null,
    lng: null,
    people_count: 708,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 233,
    region_name: "天翔",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 55,
    lat: null,
    lng: null,
    people_count: 194,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 233,
    region_name: "天翔",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 54,
    lat: null,
    lng: null,
    people_count: 149,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 233,
    region_name: "天翔",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 53,
    lat: null,
    lng: null,
    people_count: 1133,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 233,
    region_name: "天翔",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 52,
    lat: null,
    lng: null,
    people_count: 1260,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 232,
    region_name: "天域",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 51,
    lat: null,
    lng: null,
    people_count: 362,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 232,
    region_name: "天域",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 50,
    lat: null,
    lng: null,
    people_count: 252,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 232,
    region_name: "天域",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 49,
    lat: null,
    lng: null,
    people_count: 1393,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 232,
    region_name: "天域",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 48,
    lat: null,
    lng: null,
    people_count: 1289,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 231,
    region_name: "城邦",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 47,
    lat: null,
    lng: null,
    people_count: 436,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 231,
    region_name: "城邦",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 46,
    lat: null,
    lng: null,
    people_count: 308,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 231,
    region_name: "城邦",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 45,
    lat: null,
    lng: null,
    people_count: 1508,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 231,
    region_name: "城邦",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 44,
    lat: null,
    lng: null,
    people_count: 139,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 230,
    region_name: "国际水岸",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 43,
    lat: null,
    lng: null,
    people_count: 60,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 230,
    region_name: "国际水岸",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 42,
    lat: null,
    lng: null,
    people_count: 85,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 230,
    region_name: "国际水岸",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 41,
    lat: null,
    lng: null,
    people_count: 611,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 230,
    region_name: "国际水岸",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 40,
    lat: null,
    lng: null,
    people_count: 1108,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 229,
    region_name: "四季新",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 39,
    lat: null,
    lng: null,
    people_count: 362,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 229,
    region_name: "四季新",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 38,
    lat: null,
    lng: null,
    people_count: 278,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 229,
    region_name: "四季新",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 37,
    lat: null,
    lng: null,
    people_count: 1509,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 229,
    region_name: "四季新",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 36,
    lat: null,
    lng: null,
    people_count: 528,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 228,
    region_name: "双湖湾",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 35,
    lat: null,
    lng: null,
    people_count: 226,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 228,
    region_name: "双湖湾",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 34,
    lat: null,
    lng: null,
    people_count: 107,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 228,
    region_name: "双湖湾",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 33,
    lat: null,
    lng: null,
    people_count: 811,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 228,
    region_name: "双湖湾",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 32,
    lat: null,
    lng: null,
    people_count: 968,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 227,
    region_name: "加城",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 31,
    lat: null,
    lng: null,
    people_count: 293,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 227,
    region_name: "加城",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 30,
    lat: null,
    lng: null,
    people_count: 248,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 227,
    region_name: "加城",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 29,
    lat: null,
    lng: null,
    people_count: 1387,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 227,
    region_name: "加城",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 28,
    lat: null,
    lng: null,
    people_count: 538,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 226,
    region_name: "九华",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 27,
    lat: null,
    lng: null,
    people_count: 154,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 226,
    region_name: "九华",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 26,
    lat: null,
    lng: null,
    people_count: 146,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 226,
    region_name: "九华",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 25,
    lat: null,
    lng: null,
    people_count: 924,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 226,
    region_name: "九华",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 24,
    lat: null,
    lng: null,
    people_count: 795,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 225,
    region_name: "中海",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 23,
    lat: null,
    lng: null,
    people_count: 295,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 225,
    region_name: "中海",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 22,
    lat: null,
    lng: null,
    people_count: 195,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 225,
    region_name: "中海",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 21,
    lat: null,
    lng: null,
    people_count: 1406,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 225,
    region_name: "中海",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 20,
    lat: null,
    lng: null,
    people_count: 771,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 224,
    region_name: "中塘",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 19,
    lat: null,
    lng: null,
    people_count: 280,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 224,
    region_name: "中塘",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 18,
    lat: null,
    lng: null,
    people_count: 188,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 224,
    region_name: "中塘",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 17,
    lat: null,
    lng: null,
    people_count: 1128,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 224,
    region_name: "中塘",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 16,
    lat: null,
    lng: null,
    people_count: 441,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 223,
    region_name: "东湖林语",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 15,
    lat: null,
    lng: null,
    people_count: 164,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 223,
    region_name: "东湖林语",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 14,
    lat: null,
    lng: null,
    people_count: 964,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 223,
    region_name: "东湖林语",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 13,
    lat: null,
    lng: null,
    people_count: 140,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 223,
    region_name: "东湖林语",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 12,
    lat: null,
    lng: null,
    people_count: 809,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 222,
    region_name: "东湖春韵",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 11,
    lat: null,
    lng: null,
    people_count: 282,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 222,
    region_name: "东湖春韵",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 10,
    lat: null,
    lng: null,
    people_count: 183,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 222,
    region_name: "东湖春韵",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 9,
    lat: null,
    lng: null,
    people_count: 1326,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 222,
    region_name: "东湖春韵",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 8,
    lat: null,
    lng: null,
    people_count: 212,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 221,
    region_name: "东湖大郡",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 7,
    lat: null,
    lng: null,
    people_count: 94,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 221,
    region_name: "东湖大郡",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 6,
    lat: null,
    lng: null,
    people_count: 96,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 221,
    region_name: "东湖大郡",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 5,
    lat: null,
    lng: null,
    people_count: 822,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 221,
    region_name: "东湖大郡",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "网约车群体",
    id: 4,
    lat: null,
    lng: null,
    people_count: 1231,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 220,
    region_name: "东方",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "快递群体",
    id: 3,
    lat: null,
    lng: null,
    people_count: 224,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 220,
    region_name: "东方",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "外卖群体",
    id: 2,
    lat: null,
    lng: null,
    people_count: 1177,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 220,
    region_name: "东方",
  },
  {
    data_type: "新就业群体数量",
    date: "2025-05-28 00:00:00",
    distribution_type: null,
    group_type: "代驾群体",
    id: 1,
    lat: null,
    lng: null,
    people_count: 360,
    percentage: null,
    profile_category: null,
    profile_subcategory: null,
    region_id: 220,
    region_name: "东方",
  },
];
